Fix name clash of default_delete
@matthiasrichter
Could 'using default_delete' be moved into o2::framework namespace? It caused some name clash when using O2 DPL inside QualityControl:
/home/pkonopka/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/lib/../include/Framework/InputRecord.h:63:26: error: unknown template name 'default_delete'
  class Deleter : public default_delete<T>