[O2-1252] DPL: make session id configurable from command line again
FairMQ uses a session id (string) to set namespaces for shared memory regions, the
default argument is 'default'. Since 2b19ec21, DPL sets a session id string created
from the pid of the driver process, making it impossible to set the argument from the
command line.

Fixes:
   Error: option '--session' cannot be specified more than once