Add missing <functional> library include
Without this compilation fails on GCC 7.2.1 with
error: ‘function’ in namespace ‘std’ does not name a template type

Probably this was hidden by some implicit inclusion of
<functional> so far.